export type { DiagnosticPlugin } from './core/plugin.js'
export { registry } from './core/registry.js'
export type { DiagnosticContext, DiagnosticResult, OutputData, PluginOption } from './core/types.js'
export { registerBuiltinPlugins } from './plugins/index.js'
export { InspectorSession } from './services/inspector-session.js'
export { createOutputFormatter } from './services/output-formatter.js'
